AllCops:
  TargetRubyVersion: 2.6
  SuggestExtensions: false
  EnabledByDefault: true
  Exclude:
    - 'bin/*'
    - 'vendor/bundle/**/*'
    - 'spec/**/*'
    - 'test/**/*'

Style/ClassMethodsDefinitions:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/RedundantLineBreak:
  Enabled: false

Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLines:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/ClassLength:
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 12

Style/Alias:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  Enabled: false

Layout/ExtraSpacing:
  Enabled: false

Layout/SingleLineBlockChain:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 12

Layout/ClassStructure:
  Enabled: false

Style/OpenStructUse:
  Enabled: true

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/LambdaCall:
  Enabled: false

Style/OptionHash:
  Enabled: false

Style/QuotedSymbols:
  Enabled: true

Style/ReturnNil:
  Enabled: true
  EnforcedStyle: return

Style/ArrayCoercion:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/StringChars:
  Enabled: true

Style/TopLevelMethodDefinition:
  Enabled: true

Style/RedundantArgument:
  Enabled: true

Lint/MissingSuper:
  Enabled: false

Style/Documentation:
  Enabled: true

Style/ClassAndModuleChildren:
  Enabled: false

Naming/BlockForwarding:
  Enabled: true

Style/ImplicitRuntimeError:
  Enabled: false

Style/InPatternThen:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: false

Style/ModuleFunction:
  EnforcedStyle: extend_self

Style/MissingElse:
  Enabled: false

Lint/NumberConversion:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/InlineComment:
  Enabled: false

Layout/FirstHashElementLineBreak:
  Enabled: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: false

Style/ConstantVisibility:
  Enabled: false

Layout/FirstArrayElementLineBreak:
  Enabled: false

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Bundler/GemComment:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/IfUnlessModifier:
  Enabled: false
